defaults: &defaults
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: obdb_development

test:
  <<: *defaults
  database: obdb_test

production:
  <<: *defaults
  database: obdb_production
